repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.12.0"
    hooks:
      - id: hadolint #Lint Dockerfiles
        args: [--ignore, DL3018]
  - repo: https://github.com/google/yamlfmt
    rev: "v0.11.0"
    hooks:
      - id: yamlfmt #Format YAML files
        exclude: 'helm.*|.*\/templates\/.*|environments.yaml'
  - repo: https://github.com/sirwart/ripsecrets
    rev: "v0.1.8"
    hooks:
      - id: ripsecrets #Prevent committing secret keys
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.23"
    hooks:
      - id: helmlint #Lint Helm files
default_stages: [pre-commit, pre-push]
