name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: DeployToProduction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: DORA deployment frequency
        uses: DeveloperMetrics/deployment-frequency@main
        with:
          workflows: 'Deploy to Production'
      - name: Log Deployment
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/thiagop4z/test-octolense/deployments \
          -d '{"deployment_time": "$(date)", "branch": "main"}'
      - name: Log to Victoria
        run: |
          curl \
          -X POST \
          -H "Content-Type: application/json" \
          https://victoria.usln.rocks/loki/api/v1/push \
          -d '{"deployment_time": "$(date)", "branch": "main"}'
